### ISSUE TITLE
Bug: Add comments funktioniert nicht mehr!

### ISSUE THREAD

**Issue by alexweinhart** [kapadia90/ABAP#34]
Markus kannst du dich darum kümmern? :)

**Comment by ghost** [comment]
Hab die IDs in CHAR(8) geändert und leading zeros hinzugefügt, dadurch funktioniert die Sortierung und dadurch kann man auch wieder Kommentare hinzufügen. Musste aber im Zuge dessen alle Tabelleninhalte löschen - hab das meiste wieder hinzugefügt, aber könnt gerne noch mehr Tickets hinzufügen.

Hab übrigens auch die Passwörter der User in lower case geändert, dachte, das wäre easier :)
