### ISSUE TITLE
Maschinen Screen erstellen

### ISSUE THREAD

**Issue by kapadia90** [kapadia90/ABAP#4]
Wie du willst

**Comment by ghost** [comment]
Ersten Draft erstellt.

Habe nach diversen Experimenten mit den (älteren) TableControls und etwas Recherche im Internet mich dafür entschieden, ein ALV (SAP List Viewer) für die Darstellung der Übersicht zu verwenden. Das hat vor allem den Vorteil, dass man Filterung, Suche etc. alles geschenkt bekommt.

Aktuell ist es irgendwie noch gebuggt, dass es zu viele Spalten sind, aber prinzipiell müsste das so hinhauen. Um das nachzumachen, müsst ihr nur den Code im PBO kopieren, anpassen und im Screen einen Custom Container einzufügen.

Hier noch ein Thread mit Beispiel-Code, an dem ich mich orientiert habe:

https://scn.sap.com/thread/83894

PS: Für die TableControls musste ich die Strings im Dictionary in Chars umändern. Kann sein, dass es im ALV auch mit Strings geht, wäre cool, wenn ihr das rausfinden könntet.

PPS: Anand, ich hatte beim verändern des Dictionaries noch einen anderen Transport Request (...598 statt ...600) drin. Kannst du mal checken, dass wirklich alles in einem Transport Request ist?

**Comment by alexweinhart** [comment]
@MrNoodleBox :

"See the notes 857823, 910300 and 959775. All these say there is a limitation of 128 characters but does not explain why.

857823 - ALV grid: Strings with a maximum of 128 characters
**Symptom:**
Entries in cells of the type CHAR or string are truncated after 128
characters in the SAP GUI.
**More Terms:**
ALV Grid Control (cl_gui_alv_grid), function module (Full-screen) Grid
(Reuse_alv_grid_display, SAPLSLVC_FULLSCREEN), SAPGUI, back end, front end
**Cause and Prerequisites:**
The data table that is sent to the front end only allows character values
with the length 128.
**Solution:**
This is the standard system behavior and cannot be changed."
