### ISSUE TITLE
Controller implementieren

### ISSUE THREAD

**Issue by kapadia90** [kapadia90/ABAP#7]

**Comment by ghost** [comment]
Controller-Klasse angelegt und Beispiel-Funktionen für MCHN-Tabelle erstellt. Bitte für die anderen Tabellen analog implementieren.

**Comment by kapadia90** [comment]
Controller-Klasse mit User-Funktionen erweitert.

**Comment by alexweinhart** [comment]
Controller-Klasse mit Ticket-Funktion erweitert.
