### ISSUE TITLE
Subscreens erstellen (Erstellen, Editieren, Löschen)

### ISSUE THREAD

**Issue by kapadia90** [kapadia90/ABAP#9]

**Comment by kapadia90** [comment]
Nummerierung der Subscreens z.B. 201, 202, 203

**Comment by ghost** [comment]
Hab mal am Beispiel der 'Add machine'-Funktion ein funktionierendes Beispiel erstellt, an dem ihr euch orientieren könnt, um das Wechseln des Subscreens umzusetzen. Wichtig ist nur, dass ihr das fixe '0200' etc. im Subscreen-Code des Tabstrips durch eine Variable ersetzt, und die verändert ihr einfach.

**Comment by ghost** [comment]
Machine-Subscreens done.

**Comment by alexweinhart** [comment]
To-Be Done:
- Für User und Ticket: Creation Date autiomatisch einfügen
- Für alle: ID-Creater implementieren
